---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-staging
  annotations:
    linkerd.io/inject: enabled
  {{- if .Values.registry.certificateSecretNamespace }}
  labels:
    # label so that kubed copies epinio-registry secret to this namespace
    kubed-registry-tls-from: {{ .Values.registry.certificateSecretNamespace }}
  {{- end }}
