apiVersion: v2
name: epinio-application
description: The helm chart for epinio applications to be deployed by
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
home: https://github.com/epinio/epinio
type: application
version: 0.1.12
maintainers:
- email: team@epinio.io
  name: SUSE
