apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    {{- include "epinio-application.labels" . | nindent 4 }}
  name: {{ include "epinio-truncate" (print "s-" .Values.epinio.appName) }}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "epinio-application.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    {{- include "epinio-application.labels" . | nindent 4 }}
  name: {{ include "epinio-truncate" (print "s-" .Values.epinio.appName "-headless" )}}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: None
  selector:
    {{- include "epinio-application.selectorLabels" . | nindent 4 }}