apiVersion: v1
appVersion: v0.0.1-18-noassets
description: Deploys Epinio and dependencies automatically
home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
maintainers:
- email: team@epinio.io
  name: epinio
  url: https://epinio.io/
name: epinio-installer
sources:
- https://github.com/epinio/helm-charts
version: 0.4.0
