apiVersion: v1
name: epinio-installer
version: 0.4.0
# This is the version of the epinio/installer image
appVersion: v0.0.1-18
description: Deploys Epinio and dependencies automatically
home: https://github.com/epinio/epinio
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
keywords:
- epinio
- paas
sources:
- https://github.com/epinio/helm-charts
maintainers:
- name: epinio
  email: team@epinio.io
  url: https://epinio.io/
