## Default values for Epinio Helm Chart.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

# Domain which serves the Rancher UI (to access the API)
# accessControlAllowOrigin: ""

# The email address you are planning to use for getting notifications about your certificates. (default "epinio@suse.com")
email: "epinio@suse.com"

# The name of the cluster issuer to use. Epinio creates three options: 'epinio-ca', 'letsencrypt-production', and 'selfsigned-issuer'. (default "epinio-ca")
tlsIssuer: "epinio-ca"

ingress:
  # The ingressClassName is used to select the ingress controller. If empty no class will be added to the ingresses.
  ingressClassName: ""

# The domain you are planning to use for Epinio. Should be pointing to the traefik public IP (mandatory option).
domain: "localhost.omg.howdoi.website"

# The user name for authenticating all API requests.
# user: ""

# The password for authenticating all API requests.
# password: ""

# Assert to epinio that cert-manager is already installed.
# skipCertManager: false

# Skip to use existing Linkerd installation or none
# skipLinkerd: false

# Skip installation of traefik
# skipTraefik: false

# If you are using your own S3 compatible object storage for blobs, set the following options:
# s3Endpoint: ""
# s3AccessKeyId: ""
# s3SecretAccessKey: ""
# s3Bucket: ""

# Optional
# s3Location: ""
s3UseSSL: false

minio:
  enabled: true

# If you are using your own external registry, set the following options:
# externalRegistryURL: ""
# externalRegistryUsername: ""
# externalRegistryPassword: ""

# Optional
# Provide namespace (or organization) of the external registry to which you have push access. It can be left empty.
# externalRegistryNamespace: ""

# Use TLS when application images will be pulled by kubernetes. Only applies to the internal registry. (default "false")
# --force-kube-internal-registry-tls: ""

containerRegistryChart: "https://github.com/epinio/helm-charts/releases/download/container-registry-0.1.0/container-registry-0.1.0.tgz"
epinioChart: "https://github.com/epinio/helm-charts/releases/download/epinio-0.4.0/epinio-0.4.0.tgz"
traefikChart: "https://helm.traefik.io/traefik/traefik-10.3.4.tgz"
# installerImageOverride: "ghcr.io/epinio/epinio-installer:latest"

# needs to be in the .Release.Namespace
# manifestSecret: epinio

# Trace level for the install/uninistall hooks
traceLevel: "2"

server:
  traceLevel: "2"
  timeoutMultiplier: 1
