apiVersion: v2
dependencies:
- name: influxdb
  repository: https://helm.influxdata.com
  version: 4.12.5
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.0.6
description: A Helm chart for Kubernetes
maintainers:
- email: epinio@krum.io
  name: Krumware
- email: team@epinio.io
  name: SUSE
name: upgrade-responder
version: 0.2.0
