apiVersion: v2
dependencies:
- name: influxdb
  repository: https://helm.influxdata.com
  version: 4.12.0
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.50.5
description: A Helm chart for Kubernetes
maintainers:
- email: team@epinio.io
  name: SUSE
name: upgrade-responder
version: 0.3.0
