apiVersion: v1
description: A Helm chart for Kubernetes
name: upgrade-responder
version: v0.1.5
dependencies:
- name: influxdb
  repository: https://helm.influxdata.com
  version: 4.12.0
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.45.1
