{{ if not .Values.manifestSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: manifest
stringData:
  manifest.yaml: |
    {{ $registryUsername := default "admin" .Values.externalRegistryUsername -}}
    {{- $registryPassword := default (randAlphaNum 10) .Values.externalRegistryPassword -}}
    {{- $oldkeys := (lookup "v1" "Secret" "minio-epinio" "tenant-creds").data -}}
    {{- $accessKey := empty $oldkeys | ternary (randAlphaNum 16) (b64dec (default "" $oldkeys.accesskey)) -}}
    {{- $secretKey := empty $oldkeys | ternary (randAlphaNum 16) (b64dec (default "" $oldkeys.secretkey)) -}}
    {{- $sessionKey := randAlphaNum 24 -}}
    {{- $password := randAlphaNum 12 }}
    ---
    components:
      {{- if not .Values.skipLinkerd }}
      - id: linkerd
        type: yaml
        source:
          path: assets/installer/linkerd-job.yaml
        waitComplete:
          - type: "job"
            selector: "linkerd-install"
            namespace: linkerd
      {{ end }}

      {{- if not .Values.skipTraefik }}
      - id: traefik
        {{- if not .Values.skipLinkerd }}
        needs: linkerd
        {{- end }}
        namespace: traefik
        type: helm
        source:
          name: traefik
          url: {{ .Values.traefikChart | quote }}
        waitComplete:
          - type: "pod"
            selector: "app.kubernetes.io/name=traefik"
          - type: "loadbalancer"
            selector: "traefik"
        values:
          - name: globalArguments
            value: ""
          - name: "deployment.podAnnotations.linkerd\\.io/inject"
            value: "enabled"
          - name: "ports.web.redirectTo"
            value: "websecure"
          - name: "ingressClass.enabled"
            value: "true"
          - name: "ingressClass.isDefaultClass"
            value: "true"
          - name: "service.spec.loadBalancerIP"
            value: "{{ .Values.loadbalancerIP }}"
      {{ end }}

      - id: kubed
        namespace: kubed
        type: helm
        source:
          name: kubed
          path: assets/installer/kubed-v0.12.0.tgz

      {{- if not (or .Values.skipCertManager .Values.useCustomTlsIssuer) }}
      - id: cert-manager
        namespace: cert-manager
        type: helm
        source:
          name: cert-manager
          path: assets/installer/cert-manager-v1.5.4.tgz
        values:
          - name: "installCRDs"
            value: "true"
          - name: "extraArgs[0]"
            value: "--enable-certificate-owner-ref=true"
        waitComplete:
          - type: "pod"
            selector: "app.kubernetes.io/name=webhook"
            namespace: "cert-manager"
          - type: "pod"
            selector: "app.kubernetes.io/name=cainjector"
            namespace: "cert-manager"
          - type: "pod"
            selector: "app.kubernetes.io/name=cert-manager"
            namespace: "cert-manager"
      {{ end }}

      - id: namespace-epinio
        {{- if not .Values.skipLinkerd }}
        needs: linkerd
        {{- end }}
        type: namespace
        namespace: epinio
        values:
          - name: linkerd.io/inject
            value: enabled
            type: annotation

      - id: epinio
        needs: namespace-epinio
        namespace: epinio
        type: helm
        source:
          name: epinio
          path: "{{ .Values.epinioChart }}"
        values:
          - name: email
            value: "{{ .Values.email }}"
          - name: "domain"
            value: "{{ .Values.domain }}"
          - name: "api.username"
            value: {{ default "admin" .Values.user | quote }}
          - name: "api.password"
            value: {{ default $password .Values.password | quote }}
          - name:  "certManagerNamespace"
            value: cert-manager
          - name: "server.sessionKey"
            value: "{{ $sessionKey }}"
          - name: "server.accessControlAllowOrigin"
            value: {{ default "*" .Values.accessControlAllowOrigin | quote }}
          - name: "server.tlsIssuer"
            value: {{ default .Values.tlsIssuer .Values.customTlsIssuer | quote }}
          - name: "server.timeoutMultiplier"
            value: {{ .Values.server.timeoutMultiplier }}
          - name: "server.traceLevel"
            value: "{{ .Values.server.traceLevel }}"
          {{ if .Values.ingress.ingressClassName }}
          - name: "server.ingressClassName"
            value: "{{ .Values.ingress.ingressClassName }}"
          - name: "ingress.ingressClassName"
            value: "{{ .Values.ingress.ingressClassName }}"
          {{ end }}

          - name: "minio.enabled"
            value: {{ .Values.minio.enabled }}
          - name: "s3.endpoint"
            value: {{ .Values.s3Endpoint | quote }}
          - name: "s3.bucket"
            value: {{ .Values.s3Bucket | quote }}
          - name: "s3.accessKeyID"
            value: {{ .Values.s3AccessKeyId | quote }}
          - name: "s3.secretAccessKey"
            value: {{ .Values.s3SecretAccessKey | quote }}
          - name: "s3.region"
            value: {{ .Values.s3Location | quote }}
          - name: "s3.useSSL"
            value: {{ .Values.s3UseSSL }}

          - name: "registry.url"
            value: {{ default (print "epinio-registry." .Values.domain)  .Values.externalRegistryURL | quote }}
          {{- if not .Values.externalRegistryURL }}
          - name: "registry.localhostURL"
            value: "127.0.0.1:30500"
          {{- end }}
          - name: "registry.username"
            value: "{{ $registryUsername }}"
          - name: "registry.password"
            value: "{{ $registryPassword }}"
          - name: "registry.namespace"
            value: {{ default "apps" .Values.externalRegistryNamespace | quote }}
          {{- if not .Values.externalRegistryURL }}
          - name: "registry.certificateSecret"
            value: "epinio-registry-tls"
          - name: "registry.certificateSecretNamespace"
            value: "epinio-registry"
          {{- end }}
          - name: "server.forceKubeInternalRegistryTLS"
            value: {{ default "false" .Values.forceKubeInternalRegistryTLS | quote }}
        preDeploy:
          - type: "pod"
            selector: "app.kubernetes.io/name=webhook"
            namespace: "cert-manager"

      {{ if not .Values.externalRegistryURL -}}
      - id: namespace-registry
        {{- if not .Values.skipLinkerd }}
        needs: linkerd
        {{- end }}
        type: namespace
        namespace: epinio-registry
        values:
          - name: linkerd.io/inject
            value: enabled
            type: annotation

      - id: registry
        {{- if not (or .Values.skipCertManager .Values.useCustomTlsIssuer) }}
        needs: cert-manager
        {{- end }}
        namespace: epinio-registry
        type: helm
        source:
          name: epinio-registry
          path: {{ .Values.containerRegistryChart | quote }}
        values:
          - name: domain
            value: "epinio-registry.{{ .Values.domain }}"
          - name: "auth.htpasswd"
            # The only supported password format is bcrypt
            value: {{ htpasswd $registryUsername $registryPassword | quote }}
          - name: createNodePort
            value: "true"
          - name: tlsIssuer
            value: {{ default .Values.tlsIssuer .Values.customTlsIssuer | quote }}
          {{- if .Values.ingress.ingressClassName }}
          - name: "ingress.ingressClassName"
            value: "{{ .Values.ingress.ingressClassName }}"
          {{-  end }}
        preDeploy:
          - type: "pod"
            selector: "app.kubernetes.io/name=webhook"
            namespace: cert-manager
          - type: "crd"
            selector: "certificates.cert-manager.io"
          - type: "crd"
            selector: "clusterissuers.cert-manager.io"
      {{ end }}
{{ end }}
