apiVersion: batch/v1
kind: Job
metadata:
  name: "post-install-{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
    "linkerd.io/inject": disabled
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: epinio-installer
      containers:
      - name: install
        image: {{ template  "epinio.installerImage" . }}
        imagePullPolicy: IfNotPresent
        workingDir: /
        command:
          - /usr/local/bin/epinio-installer
        args:
          - install
          - --trace-level
          - "{{ .Values.traceLevel }}"
          - -m
          - /etc/epinio/manifest.yaml
        volumeMounts:
        - name: manifest
          mountPath: /etc/epinio/
      volumes:
        - name: manifest
          secret:
            secretName: manifest
